<?php

/**
 * @file
 * Install, update and uninstall functions for the Magnific Popup module.
 */

/**
 * Implements hook_requirements().
 */
function magnific_popup_requirements($phase) {
  $requirements = [];

  if ($phase == 'runtime') {
    $requirements['magnific_popup']['title'] = t('Magnific Popup Library');

    // Verify library files are present.
    if (file_exists(DRUPAL_ROOT . '/libraries/magnific_popup/jquery.magnific-popup.min.js') && file_exists(DRUPAL_ROOT . '/libraries/magnific_popup/magnific-popup.css')) {
      $requirements['magnific_popup']['value'] = t('Installed');
      $requirements['magnific_popup']['severity'] = REQUIREMENT_OK;
    }
    else {
      $requirements['magnific_popup']['value'] = t('Not Installed');
      $requirements['magnific_popup']['severity'] = REQUIREMENT_ERROR;
      $requirements['magnific_popup']['description'] = t('Please download the Magnific Popup Library from :url and copy the contents of the "dist" folder to DRUPAL_ROOT/libraries/magnific_popup.', [':url' => 'https://github.com/dimsemenov/Magnific-Popup/releases']);
    }
  }

  return $requirements;
}
